const statusLine=document.getElementById('editor-status');
const announce=message=>{statusLine.textContent=message;};
const imageDatabase=new Promise((resolve,reject)=>{const request=indexedDB.open('karthik-portfolio-images',1);request.onupgradeneeded=()=>request.result.createObjectStore('images');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});
imageDatabase.catch(()=>{});
async function storedImage(action,key,value){const db=await imageDatabase;return new Promise((resolve,reject)=>{const tx=db.transaction('images',action==='get'?'readonly':'readwrite');const store=tx.objectStore('images');const request=action==='put'?store.put(value,key):action==='delete'?store.delete(key):store.get(key);let result;request.onsuccess=()=>{result=request.result;};tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);});}
function applyImage(id,src,custom){document.getElementById(id).querySelector('img').src=src;}
const asDataURL=blob=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob);});
for(const [id] of skills){storedImage('get',id).then(data=>{if(data)applyImage(id,data,true);}).catch(()=>{});}
document.querySelectorAll('[data-upload]').forEach(input=>input.addEventListener('change',async()=>{const file=input.files[0];if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)){announce('Please choose a PNG, JPG, or WebP image.');input.value='';return;}if(file.size>15*1024*1024){announce('Please choose an image smaller than 15 MB.');input.value='';return;}try{const data=await asDataURL(file);const check=new Image();check.src=data;await check.decode();applyImage(input.dataset.upload,data,true);try{await storedImage('put',input.dataset.upload,data);announce('Image saved in this browser. Export your website to publish it.');}catch{announce('Image updated for this visit. Browser storage is unavailable; export now to keep it.');}}catch{announce('This image could not be opened. Please try another file.');}input.value='';}));
document.querySelectorAll('[data-reset]').forEach(button=>button.addEventListener('click',async()=>{const id=button.dataset.reset;try{await storedImage('delete',id);applyImage(id,bundledImages[id]||portfolioImagePath(id,0),false);announce('Original image restored.');}catch{announce('Could not reset the saved image. Please try again.');}}));
document.getElementById('export-site').addEventListener('click',async event=>{const button=event.currentTarget;button.disabled=true;announce('Preparing your complete website with all images…');try{const assets={};await Promise.all(skills.map(async([id])=>{const src=document.getElementById(id).querySelector('img').src;if(src.startsWith('data:'))assets[id]=src;else{const response=await fetch(src);if(!response.ok)throw new Error('image');assets[id]=await asDataURL(await response.blob());}}));const featureAssets={};await Promise.all(skills.flatMap(([id])=>[1,2].map(async index=>{const src=featureImageSource(id,index);if(src.startsWith('data:'))featureAssets[`${id}-${index}`]=src;else{const response=await fetch(src);if(!response.ok)throw new Error('feature image');featureAssets[`${id}-${index}`]=await asDataURL(await response.blob());}})));const clone=document.documentElement.cloneNode(true);clone.querySelector('#bundled-features')?.remove();clone.querySelector('#feature-dialog')?.remove();const featureBundle=document.createElement('script');featureBundle.id='bundled-features';featureBundle.type='application/json';featureBundle.textContent=JSON.stringify(featureAssets);clone.querySelector('head').append(featureBundle);clone.querySelector('#bundled-images')?.remove();const bundle=document.createElement('script');bundle.id='bundled-images';bundle.type='application/json';bundle.textContent=JSON.stringify(assets).replace(/</g,'\\u003c');clone.querySelector('head').append(bundle);for(const original of document.querySelectorAll('script[data-site-script]')){const source=original.src?await fetch(original.src).then(r=>{if(!r.ok)throw new Error('script');return r.text();}):original.textContent;const target=clone.querySelector(`script[data-site-script="${original.dataset.siteScript}"]`);target.removeAttribute('src');target.textContent=source;}const stylesheet=clone.querySelector('link[rel="stylesheet"]');if(stylesheet){const response=await fetch(stylesheet.getAttribute('href'));if(!response.ok)throw new Error('styles');const style=document.createElement('style');style.textContent=await response.text();stylesheet.replaceWith(style);}clone.querySelector('#editor-status').textContent='';clone.querySelector('#export-site').removeAttribute('disabled');clone.querySelectorAll('[style]').forEach(element=>element.removeAttribute('style'));const file=new Blob(['<!doctype html>\n',clone.outerHTML],{type:'text/html;charset=utf-8'});const url=URL.createObjectURL(file);const download=document.createElement('a');download.href=url;download.download='index.html';download.click();setTimeout(()=>URL.revokeObjectURL(url),30000);announce('Website exported as index.html, including all images. Ready for a static Vercel project.');}catch{announce('Export failed. Keep this page open and try again from the local preview or your hosted website.');}finally{button.disabled=false;}});
